spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/ticketstore-flutter/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/ticketstore-flutter #la porta 8080 va messa?
  application:
    name: TicketStore
  datasource:
    password: 'tatadada58gial'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    url: jdbc:mysql://localhost:3306/ticketstore?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

  server:
    #ssl:
    #key-store-password: password_certificate
    #key-store-type: PKCS12
    #key-store: /home/debian/ssl-cert/certificate.p12
    compression:
      enabled: 'true'
    port: '9090'



  keycloack:
    resource: ticketstore-flutter

  logging:
    level:
      it:
        frankladder: DEBUG
      org:
        springframework: INFO

  debug: false