spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8443/auth/realms/rendicontation/protocol/openid-connect/certs
          issuer-uri: http://localhost:8443/auth/realms/rendicontation
  application:
      name: TicketStore
  datasource:
    password: 'tatadada58gial'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    url: jdbc:mysql://localhost:3306/ticketstore?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect